spring:
  metadataentity: MetaDataEntity
  schedule: 0 0 1 * * ?
  datasource:
    url: jdbc:mysql://192.168.11.130:3306/dmp_datamanagement_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver

  # redis
  redis:
    host: 192.168.11.130
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true
#授权
fk:
  auth:
    clientId: datamanagement-service
    secret: 1234
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 6

#atlas配置
atlas:
  account: admin
  password: admin
  searchBasic: /api/atlas/v2/search/basic
  entityByGuid: /api/atlas/v2/entity/guid
  entity: /api/atlas/v2/entity
  typedefs: /api/atlas/v2/types/typedefs
  delTypeDefs: /api/atlas/v2/types/typedef/name/
  bulkClassification: /api/atlas/v2/entity/bulk/classification
  lineage: /api/atlas/v2/lineage
  relationship: /api/atlas/v2/relationship
  searchQuick: /api/atlas/v2/search/quick
  searchSuggestions: /api/atlas/v2/search/suggestions
  glossary:
    url: /api/atlas/v2/glossary
    term: /api/atlas/v2/glossary/term
    terms: /api/atlas/v2/glossary/terms
    category: /api/atlas/v2/glossary/category
  request:
    url: http://192.168.1.250:21000

#元数据对象配置
fidata:
  database:
    name: 192.168.1.250,192.168.1.250,192.168.11.134
    hostname: 192.168.1.250,192.168.1.250,192.168.11.134
    port: 5432,5432,9030
    platform: Linux,Linux,Linux
    protocol: http,http,http
    rdbmstype: postgresql,postgresql,doris
    username: postgres,postgres,root
    password: Password01!,Password01!,Password01!
    db: dmp_ods,dmp_dw,dmp_olap

#血缘同步
scheduling:
  enabled: true

#feign接口超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 12000

ribbon:
  eager-load:
    enabled: true
    clients: datamodel-service,dataaccess-service

  hystrix:
    command:
    default:
      isolation:
        thread:
          timeoutInMilliseconds: 30000
      execution:
        timeout:
          enabled: true