spring:
  metadataentity: MetaDataEntity
  schedule: 0 0 2 * * ?
  datasource:
    url: jdbc:mysql://100.102.201.107:3307/dmp_datamanagement_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: .FdF_r&tj4)+
    driver-class-name: com.mysql.jdbc.Driver

# redis
  redis:
    host: 10.220.108.140
    port: 16380
    password: test123456
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true

#授权
fk:
  auth:
    clientId: datamanagement-service
    secret: 1234
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 6

#atlas配置
atlas:
  account: admin
  password: admin
  searchBasic: /api/atlas/v2/search/basic
  entityByGuid: /api/atlas/v2/entity/guid
  entity: /api/atlas/v2/entity
  typedefs: /api/atlas/v2/types/typedefs
  delTypeDefs: /api/atlas/v2/types/typedef/name/
  bulkClassification: /api/atlas/v2/entity/bulk/classification
  lineage: /api/atlas/v2/lineage
  relationship: /api/atlas/v2/relationship
  searchQuick: /api/atlas/v2/search/quick
  searchSuggestions: /api/atlas/v2/search/suggestions
  glossary:
    url: /api/atlas/v2/glossary
    term: /api/atlas/v2/glossary/term
    terms: /api/atlas/v2/glossary/terms
    category: /api/atlas/v2/glossary/category
  request:
    url: http://100.102.201.108:21000

#元数据对象配置
fidata:
  database:
    name: 100.102.201.107,100.102.201.107,100.102.201.107
    hostname: 100.102.201.107,100.102.201.107,100.102.201.107
    port: 5433,5433,9030
    platform: Linux,Linux,Linux
    protocol: http,http,http
    rdbmstype: postgresql,postgresql,doris
    username: adminuser,adminuser,root
    password: .FdF_r&tj4)+,.FdF_r&tj4)+,.FdF_r&tj4)+
    db: dmp_ods,dmp_dw,dmp_olap

#血缘同步
scheduling:
  enabled: true

#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka

#feign接口超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 12000

ribbon:
  eager-load:
    enabled: true
    clients: datamodel-service,dataaccess-service

hystrix:
  command:
  default:
    isolation:
      thread:
        timeoutInMilliseconds:  30000
    execution:
      timeout:
        enabled: true