package com.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.5.7
 * 2023-12-04T10:53:13.551+08:00
 * Generated source version: 3.5.7
 *
 */
@WebService(targetNamespace = "http://ws.ksf.com.cn/", name = "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap {

    @WebMethod(operationName = "Operation_ZALLSAP_UPLOAD_GOODSMOV", action = "http://ws.ksf.com.cn/ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingT/Operation_ZALLSAP_UPLOAD_GOODSMOV")
    @WebResult(name = "Operation_ZALLSAP_UPLOAD_GOODSMOVResponse", targetNamespace = "http://ws.ksf.com.cn/", partName = "parameters")
    public OperationZALLSAPUPLOADGOODSMOVResponse operationZALLSAPUPLOADGOODSMOV(

        @WebParam(partName = "parameters", name = "Operation_ZALLSAP_UPLOAD_GOODSMOV", targetNamespace = "http://ws.ksf.com.cn/")
        OperationZALLSAPUPLOADGOODSMOV parameters
    );
}
