package com.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * BizTalk assembly "ZALLSAP_UPLOAD_GOODSMOV, Version=1.0.0.0, Culture=neutral, PublicKeyToken=6275dafe1412b913" published web service.
 *
 * This class was generated by Apache CXF 3.5.7
 * 2023-12-04T10:53:13.578+08:00
 * Generated source version: 3.5.7
 *
 */
@WebServiceClient(name = "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingT",
                  wsdlLocation = "http://tws.ksf.com.cn:8899/ZALLSAP_UPLOAD_GOODSMOV_Proxy/ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingT.asmx?wsdl",
                  targetNamespace = "http://ws.ksf.com.cn/")
public class ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.ksf.com.cn/", "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingT");
    public final static QName ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap12 = new QName("http://ws.ksf.com.cn/", "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap12");
    public final static QName ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap = new QName("http://ws.ksf.com.cn/", "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://tws.ksf.com.cn:8899/ZALLSAP_UPLOAD_GOODSMOV_Proxy/ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingT.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://tws.ksf.com.cn:8899/ZALLSAP_UPLOAD_GOODSMOV_Proxy/ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingT.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingT(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap
     */
    @WebEndpoint(name = "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap12")
    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap getZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap12() {
        return super.getPort(ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap12, ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap
     */
    @WebEndpoint(name = "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap12")
    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap getZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap12(WebServiceFeature... features) {
        return super.getPort(ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap12, ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap.class, features);
    }


    /**
     *
     * @return
     *     returns ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap
     */
    @WebEndpoint(name = "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap")
    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap getZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap() {
        return super.getPort(ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap, ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap
     */
    @WebEndpoint(name = "ZALLSAP_UPLOAD_GOODSMOV_Orchestration_1_Port_DingTSoap")
    public ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap getZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap(WebServiceFeature... features) {
        return super.getPort(ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap, ZALLSAPUPLOADGOODSMOVOrchestration1PortDingTSoap.class, features);
    }

}
