spring:
  application:
    name: datagovernance-service
  datasource:
    url: jdbc:mysql://192.168.11.130:3306/dmp_datagovernance_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.11.130

mybatis-plus:
  configuration:
    default-enum-type-handler: com.fisk.common.mybatis.config.BaseEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      logic-delete-field: del_flag
      logic-delete-value: 0
      logic-not-delete-value: 1
      update-strategy: not_null
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fisk.datagovernance.entity

fk:
  auth:
    clientId: datagovernance-service
    secret: 1234
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 6

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
