spring:
  datasource:
    url: jdbc:mysql://10.220.108.140:13307/dmp_datainput_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: .FdF_r&tj4)+
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      datasource:
        taskdb:
          url: jdbc:mysql://100.102.201.107:3307/dmp_task_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: root
          password: .FdF_r&tj4)+
          driver-class-name: com.mysql.jdbc.Driver

# redis
  redis:
    host: 10.220.108.140
    port: 16380
    password: test123456
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true
# pdf文档模板
dataservice:
  pdf:
    path: /data/java/fisk-factory-access/pdf
    # 接口文档中的环境信息
    uat_address: http://10.220.108.140:10089
    prd_address: https://prdHost

# 数据质量校验的信息(ip: pg数据源的ip地址; dbName: 连接的ods库)
Data-quality-check:
  ip: 100.102.201.107
  dbName: dmp_ods

# 元数据实例信息
metadata-instance:
  # 数据库类型
  rdbmsType: postgresql
  # 平台
  platform: Linux
  # 主机
  hostname: 100.102.201.107
  # 端口
  port: 5433
  # 数据库
  dbName: dmp_ods
  # 网络协议
  protocol: http

flink-config:
  host: 192.168.11.131
  port: 22
  user: root
  password: Password01!
  upload-path: /root/flink-job/sql/
  upload-way: ssh
  savepoints-path: /root/flink-job/savepoint/
  command: dev
  command-path: /root/flink/flink-1.15.2/bin/sql-client.sh

flink-api-config:
  host: http://192.168.11.131
  port: 8081
  savepoints: /jobs/:jobid/savepoints
  savepoint-status: /jobs/:jobid/savepoints/:triggerid