spring:
  datasource:
    url: jdbc:mysql://10.195.135.247:3306/dmp_datainput_db_v2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: nifi_owne
    password: ABCabc1234
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      datasource:
        taskdb:
          url: jdbc:mysql://10.195.135.247:3306/dmp_task_db_v2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: nifi_owne
          password: ABCabc1234
          driver-class-name: com.mysql.jdbc.Driver

  # redis
  redis:
    host: 10.195.135.248
    port: 6379
    password: 80405390
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true

# 是否同步元数据
open-metadata: false
# 是否开启api质量校验
open-data-check: false

# 智能发布所需配置
config-url: jdbc:mysql://192.168.11.130:3306/dmp_datainput_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
config-username: root
config-password: root123
# 配置库db类型 根据各个客户环境改变
config-driverType: MYSQL
# 配置库 tb_table_access 表名  根据各个客户环境改变
config-tb-name: tb_table_access

# pdf文档模板
dataservice:
  pdf:
    path: E:\\mycode\\20211018\\Fisk.DMP.Project\\fisk-factory-access\\fisk-factory-access-web\\target\\classes
    #    path: /root/java/fisk-factory-access/pdf
    # 接口文档中的环境信息
    uat_address: http://192.168.11.130:8083
    prd_address: https://prdHost

# 数据质量校验的信息(ip: pg数据源的ip地址; dbName: 连接的ods库)
data-quality-check:
  ip: 192.168.1.250
  dbName: dmp_ods

flink-config:
  host: 10.178.188.65
  port: 22
  user: powerbi
  password: powerbi@dev

  upload-path: /opt/fidata/flink/sqlscript/
  upload-way: ssh
  savepoints-path: /opt/fidata/flink/savepoint/
  command: yarn
  command-path: /usr/flink-1.15.2/bin/sql-client.sh

flink-api-config:
  host: http://10.178.188.65
  port: 8081
  savepoints: /jobs/:jobid/savepoints
  savepoint-status: /jobs/:jobid/savepoints/:triggerid
