spring:
  datasource:
    url: jdbc:mysql://192.168.11.130:3306/dmp_datainput_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
    dynamic:
      datasource:
        taskdb:
          url: jdbc:mysql://192.168.11.130:3306/dmp_task_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
          username: root
          password: root123
          driver-class-name: com.mysql.jdbc.Driver

# redis
  redis:
    host: 192.168.11.130
# 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true
# pdf文档模板
dataservice:
  pdf:
    path: /root/java/dataaccess/pdf

#授权
fk:
  auth:
    clientId: dataAccess-service
    secret: 1234
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 6

mybatis-plus:
  configuration:
    default-enum-type-handler: com.fisk.common.mybatis.config.BaseEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      logic-delete-field: del_flag
      logic-delete-value: 0
      logic-not-delete-value: 1
      update-strategy: not_null
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fisk.dataaccess.entity

# pg数据源配置
pgsql-datamodel:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://192.168.1.250:5432/dmp_dw?stringtype=unspecified
  username: postgres
  password: Password01!
pgsql-ods:
  url: jdbc:postgresql://192.168.1.250:5432/dmp_ods?stringtype=unspecified
  username: postgres
  password: Password01!


#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka

#feign接口超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 12000
