server:
  port: 8097
spring:
  application:
    name: apiService-service
  profiles:
    active: demo
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    default-enum-type-handler: com.fisk.common.framework.mybatis.config.BaseEnumTypeHandler
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      logic-delete-field: del_flag
      logic-delete-value: 0
      logic-not-delete-value: 1
      update-strategy: not_null
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fisk.apiservice.entity

fk:
  jwt:
    key: helloWorldJavaLeyouAuthServiceSecretKey # 私钥
  auth:
    clientId: apiService-service
    secret: 1234
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 6

#feign接口超时配置
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 12000
feign:
  client:
    config:
      default:
        loggerLevel: basic
  hystrix:
    enabled: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 15000
  NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
  ServerListRefreshInterval: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          # 线程隔离 THREAD， SEMAPHORE
          strategy: THREAD
          thread:
            # 超时时间
            timeoutInMilliseconds: 15500
            # 超时时是否应中断执行（默认true）
            interruptOnTimeout: true
      circuitBreaker:
        enabled: true
        # 在滚动窗口中启用熔断的最小请求数（默认20次）
        requestVolumeThreshold: 10
        # 熔断后，多少ms后进行一次请求尝试（默认5000ms）
        sleepWindowInMilliseconds: 5000
        # 当请求错误比例到达n%时，开启熔断（默认50%）
        errorThresholdPercentage: 50