spring:
  datasource:
    url: jdbc:mysql://10.195.135.247:3306/dmp_datamodel_db_v2?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: nifi_owne
    password: ABCabc1234
    driver-class-name: com.mysql.jdbc.Driver

  # redis
  redis:
    host: 10.195.135.248
    password: 80405390
  # 防止模板报空错误
  freemarker:
    settings:
      classic_compatible: true
#授权
fk:
  auth:
    clientId: data-model-service
    secret: 1234
  encoder:
    crypt:
      secret: ${random.uuid}
      strength: 6

# 数据建模目标dw库id
fiData-data-dw-source: 1