spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.11.130:3306/dmp_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root123

  redis:
    host: 192.168.11.130

# 配置秘钥,给Jwt加密的私钥,可定期更改
fk:
  jwt:
    key: helloWorldJavaLeyouAuthServiceSecretKey # 私钥

mybatis-plus:
  global-config:
    db-config:
      id-type: auto #主键自增
      insert-strategy: not_empty #insert操作时,字段值不为空
      update-strategy: not_empty
      logic-delete-field: del_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.fisk.auth.entity #包扫描

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka
