spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.21.13:3306/FiData_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password01!
  redis:
    host: 192.168.21.13
# mdm授权账号
mdmAuthorize:
  url: http://192.168.1.32:5500/api/Integration/GetToken
  userAccount: admin
  userPassword: 123456
# 图片上传
file:
  uploadurl: /opt/0226/soft/nginx/app/file/dmp/images
  logoUrl: /opt/0226/soft/nginx/app/file/systemlogo/images
