spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.1.248:3306/dmp_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password01!

  redis:
    host: 172.17.1.248

# 图片上传
file:
  uploadurl: /root/nginx/app/file/dmp/images
