spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.1.248:3306/dmp_system_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Password01!
  redis:
    host: 172.17.1.248
# mdm授权账号
mdmAuthorize:
  url: http://192.168.1.32:5500/api/Integration/GetToken
  userAccount: admin
  userPassword: 123456
# 图片上传
file:
  uploadurl: /root/nginx/app/file/dmp/images
  logoUrl: /root/nginx/app/file/systemlogo/images
