spring:
  application:
    name: data-factory
  datasource:
    url: jdbc:mysql://10.178.188.31:3306/dmp_datafactory_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: fisksoft
    password: Fisksoft@hsd06
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.178.188.31
    password: redis@test
    port: 6379