spring:
  application:
    name: data-factory
  datasource:
    url: jdbc:mysql://10.195.131.25:3306/dmp_datafactory_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: nifi_owner
    password: ABCabc1234
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 10.195.131.21
    password: 7b80ba2c
    port: 6379